# Основные настройки приложения
spring:
  application:
    name: bank-cards
  security:
    enabled: false
  
  # Профили: default, dev, prod, docker
  profiles:
    active: dev
    include:
  
  # Настройки Datasource (переопределяются в профилях)
  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  
  # Настройки JPA
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        show_sql: false
    open-in-view: false
    generate-ddl: false
  
  # Настройки Liquibase
  liquibase:
    change-log: classpath:db/migration/changelog-master.yml
    enabled: true
    default-schema: public
  
  # MVC настройки
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# JWT настройки
jwt:
  secret: bank-cards-secret-key-2024-very-secure-and-long-32-chars
  expiration: 86400000 # 24 часа в миллисекундах

# Шифрование карт
encryption:
  secret: card-encryption-key-32-chars-123

# Логирование
logging:
  level:
    com.example.bankcards: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Server настройки
server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

# Spring Doc (Swagger)
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    default-accept: application/json
    persist-authorization: true
    display-request-duration: true
  show-actuator: true
  default-produces-media-type: application/json

# Management endpoints (для мониторинга)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true
  info:
    env:
      enabled: true

# Jackson (настройки JSON сериализации)
jackson:
  serialization:
    write-dates-as-timestamps: false
    indent-output: true
  date-format: yyyy-MM-dd HH:mm:ss
  time-zone: Europe/Moscow